### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    id: _multi_shard_result_set_internal_exception
    parent: com.microsoft.azure.elasticdb.query.exception
    children:
      - com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException()
      - com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String)
      - 'com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String,RuntimeException)'
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException
    type: Class
    source:
      remote: &ref_0
        path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
        branch: master
        repo: 'https://github.com/Microsoft/elastic-db-tools-for-java'
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 17
    package: com.microsoft.azure.elasticdb.query.exception
    summary: '<p>Benutzerdefinierte Ausnahme wird ausgelöst, wenn die MultiShardResultSet in einem ungültigen Zustand befindet. Wenn Sie diese Ausnahme wiederholt auftritt, wenden Sie sich an den Microsoft-Kundensupport. Zweck: Benutzerdefinierte Ausnahme auslösen, wenn die MultiShardResultSet in einem ungültigen Zustand ist. Dieser Fehler sollte nicht für den Benutzer erleichtern. </p>'
    syntax: &ref_1
      content: public class MultiShardResultSetInternalException
    inheritance:
      - java.lang.Object
      - RuntimeException
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException()
    id: MultiShardResultSetInternalException()
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException()
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException()
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException()
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 22
    package: com.microsoft.azure.elasticdb.query.exception
    summary: <p>Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> Klasse. </p>
    syntax:
      content: public MultiShardResultSetInternalException()
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String)
    id: MultiShardResultSetInternalException(String)
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: MultiShardResultSetInternalException(String message)
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message)
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message)
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 32
    package: com.microsoft.azure.elasticdb.query.exception
    summary: |-
      <p>Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> Klasse mit einer angegebenen Fehlermeldung.</p>
      <p></p>
    syntax:
      content: public MultiShardResultSetInternalException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: '<p>Die Meldung, die den Fehler beschreibt. </p>'
  - uid: 'com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException(String,RuntimeException)'
    id: 'MultiShardResultSetInternalException(String,RuntimeException)'
    parent: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    langs:
      - java
    name: 'MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    nameWithType: 'MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    fullName: 'com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException(String message, RuntimeException innerException)'
    overload: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    type: Constructor
    source:
      remote: *ref_0
      path: elastic-db-tools/src/main/java/com/microsoft/azure/elasticdb/query/exception/MultiShardResultSetInternalException.java
      startLine: 44
    package: com.microsoft.azure.elasticdb.query.exception
    summary: |-
      <p>Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception" data-throw-if-not-resolved="false">MultiShardResultSetInternalException</xref> Klasse mit einer Meldung und inneren Ausnahme.</p>
      <p></p>
    syntax:
      content: 'public MultiShardResultSetInternalException(String message, RuntimeException innerException)'
      parameters:
        - id: message
          type: '26831127'
          description: '<p>Die Meldung, in der Ausnahme zu kapseln. </p>'
        - id: innerException
          type: 9b2a4515
          description: '<p>Die zugrunde liegende Ausnahme, die diese Ausnahme verursacht hat. </p>'
references:
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.MultiShardResultSetInternalException*
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException.MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException.MultiShardResultSetInternalException
    package: com.microsoft.azure.elasticdb.query.exception
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: 9b2a4515
    spec.java:
      - name: RuntimeException
        fullName: RuntimeException
  - uid: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception
    parent: com.microsoft.azure.elasticdb.query.exception
    href: com.microsoft.azure.elasticdb.query.exception._multi_shard_result_set_internal_exception.yml
    name: MultiShardResultSetInternalException
    nameWithType: MultiShardResultSetInternalException
    fullName: com.microsoft.azure.elasticdb.query.exception.MultiShardResultSetInternalException
    type: Class
    summary: '<p>Benutzerdefinierte Ausnahme wird ausgelöst, wenn die MultiShardResultSet in einem ungültigen Zustand befindet. Wenn Sie diese Ausnahme wiederholt auftritt, wenden Sie sich an den Microsoft-Kundensupport. Zweck: Benutzerdefinierte Ausnahme auslösen, wenn die MultiShardResultSet in einem ungültigen Zustand ist. Dieser Fehler sollte nicht für den Benutzer erleichtern. </p>'
    syntax: *ref_1